version: "2"
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod

  nginx:
    build: ./proxy
    ports:
      - "80:80"
    links:
      - client
      - server
