version: "2"
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    
  clojure:
    build: ./clojure

  nginx:
    build: ./proxy
    ports:
      - "80:80"
    links:
      - client
      - clojure
