version: "3"

services:
  client:
    build: client
    volumes:
    - "./client:/src"
    - /src/node_modules
    working_dir: /src
    command: 'npm run dev'
    ports:
      - 6800:1998

  server:
    build: server
    volumes:
    - "./server:/src"
    working_dir: /src
    command: 'lein run'
    ports:
      - 3003:3009
